//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vits.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Deviation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Mission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Office))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Subsistence))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Trip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.TravelAdvances))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Expense))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.CostCenter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Report))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Deviation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Mission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Office))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Subsistence))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Trip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.TravelAdvances))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Expense))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.CostCenter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Report))]
    public partial class EntityObject : Vits.ServiceReference1.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deviation", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Deviation : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw ReportReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StopDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DID {
            get {
                return this.DIDField;
            }
            set {
                if ((this.DIDField.Equals(value) != true)) {
                    this.DIDField = value;
                    this.RaisePropertyChanged("DID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPID {
            get {
                return this.REPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.REPIDField, value) != true)) {
                    this.REPIDField = value;
                    this.RaisePropertyChanged("REPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw ReportReference {
            get {
                return this.ReportReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportReferenceField, value) != true)) {
                    this.ReportReferenceField = value;
                    this.RaisePropertyChanged("ReportReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StopDate {
            get {
                return this.StopDateField;
            }
            set {
                if ((this.StopDateField.Equals(value) != true)) {
                    this.StopDateField = value;
                    this.RaisePropertyChanged("StopDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Employee : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Mission> MissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Mission> Mission1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Report> ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.TravelAdvances> TravelAdvancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Trip> TripField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EID {
            get {
                return this.EIDField;
            }
            set {
                if ((this.EIDField.Equals(value) != true)) {
                    this.EIDField = value;
                    this.RaisePropertyChanged("EID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((this.ManagerField.Equals(value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Mission> Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionField, value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Mission> Mission1 {
            get {
                return this.Mission1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Mission1Field, value) != true)) {
                    this.Mission1Field = value;
                    this.RaisePropertyChanged("Mission1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Report> Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.TravelAdvances> TravelAdvances {
            get {
                return this.TravelAdvancesField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelAdvancesField, value) != true)) {
                    this.TravelAdvancesField = value;
                    this.RaisePropertyChanged("TravelAdvances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Trip> Trip {
            get {
                return this.TripField;
            }
            set {
                if ((object.ReferenceEquals(this.TripField, value) != true)) {
                    this.TripField = value;
                    this.RaisePropertyChanged("Trip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mission", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Mission : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Employee> Employee1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte OIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Office OfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfOfficeEo6k46yw OfficeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Report> ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.TravelAdvances> TravelAdvancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Trip> TripField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Employee> Employee1 {
            get {
                return this.Employee1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Employee1Field, value) != true)) {
                    this.Employee1Field = value;
                    this.RaisePropertyChanged("Employee1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReference {
            get {
                return this.EmployeeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeReferenceField, value) != true)) {
                    this.EmployeeReferenceField = value;
                    this.RaisePropertyChanged("EmployeeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((this.ManagerField.Equals(value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte OID {
            get {
                return this.OIDField;
            }
            set {
                if ((this.OIDField.Equals(value) != true)) {
                    this.OIDField = value;
                    this.RaisePropertyChanged("OID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Office Office {
            get {
                return this.OfficeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeField, value) != true)) {
                    this.OfficeField = value;
                    this.RaisePropertyChanged("Office");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfOfficeEo6k46yw OfficeReference {
            get {
                return this.OfficeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeReferenceField, value) != true)) {
                    this.OfficeReferenceField = value;
                    this.RaisePropertyChanged("OfficeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Report> Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.TravelAdvances> TravelAdvances {
            get {
                return this.TravelAdvancesField;
            }
            set {
                if ((object.ReferenceEquals(this.TravelAdvancesField, value) != true)) {
                    this.TravelAdvancesField = value;
                    this.RaisePropertyChanged("TravelAdvances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Trip> Trip {
            get {
                return this.TripField;
            }
            set {
                if ((object.ReferenceEquals(this.TripField, value) != true)) {
                    this.TripField = value;
                    this.RaisePropertyChanged("Trip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Office : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw CountryReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Mission> MissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte OIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrgNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CID {
            get {
                return this.CIDField;
            }
            set {
                if ((this.CIDField.Equals(value) != true)) {
                    this.CIDField = value;
                    this.RaisePropertyChanged("CID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw CountryReference {
            get {
                return this.CountryReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryReferenceField, value) != true)) {
                    this.CountryReferenceField = value;
                    this.RaisePropertyChanged("CountryReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Mission> Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionField, value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte OID {
            get {
                return this.OIDField;
            }
            set {
                if ((this.OIDField.Equals(value) != true)) {
                    this.OIDField = value;
                    this.RaisePropertyChanged("OID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgNumber {
            get {
                return this.OrgNumberField;
            }
            set {
                if ((this.OrgNumberField.Equals(value) != true)) {
                    this.OrgNumberField = value;
                    this.RaisePropertyChanged("OrgNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Country : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Office> OfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Subsistence> SubsistenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Trip> TripField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CID {
            get {
                return this.CIDField;
            }
            set {
                if ((this.CIDField.Equals(value) != true)) {
                    this.CIDField = value;
                    this.RaisePropertyChanged("CID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Office> Office {
            get {
                return this.OfficeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeField, value) != true)) {
                    this.OfficeField = value;
                    this.RaisePropertyChanged("Office");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Subsistence> Subsistence {
            get {
                return this.SubsistenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubsistenceField, value) != true)) {
                    this.SubsistenceField = value;
                    this.RaisePropertyChanged("Subsistence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Trip> Trip {
            get {
                return this.TripField;
            }
            set {
                if ((object.ReferenceEquals(this.TripField, value) != true)) {
                    this.TripField = value;
                    this.RaisePropertyChanged("Trip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subsistence", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Subsistence : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw CountryReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw ReportReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SUMField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CID {
            get {
                return this.CIDField;
            }
            set {
                if ((this.CIDField.Equals(value) != true)) {
                    this.CIDField = value;
                    this.RaisePropertyChanged("CID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw CountryReference {
            get {
                return this.CountryReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryReferenceField, value) != true)) {
                    this.CountryReferenceField = value;
                    this.RaisePropertyChanged("CountryReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATE {
            get {
                return this.DATEField;
            }
            set {
                if ((this.DATEField.Equals(value) != true)) {
                    this.DATEField = value;
                    this.RaisePropertyChanged("DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPID {
            get {
                return this.REPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.REPIDField, value) != true)) {
                    this.REPIDField = value;
                    this.RaisePropertyChanged("REPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw ReportReference {
            get {
                return this.ReportReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportReferenceField, value) != true)) {
                    this.ReportReferenceField = value;
                    this.RaisePropertyChanged("ReportReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SID {
            get {
                return this.SIDField;
            }
            set {
                if ((this.SIDField.Equals(value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SUM {
            get {
                return this.SUMField;
            }
            set {
                if ((this.SUMField.Equals(value) != true)) {
                    this.SUMField = value;
                    this.RaisePropertyChanged("SUM");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trip", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Trip : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw CountryReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Mission MissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw MissionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StopDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CID {
            get {
                return this.CIDField;
            }
            set {
                if ((this.CIDField.Equals(value) != true)) {
                    this.CIDField = value;
                    this.RaisePropertyChanged("CID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw CountryReference {
            get {
                return this.CountryReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryReferenceField, value) != true)) {
                    this.CountryReferenceField = value;
                    this.RaisePropertyChanged("CountryReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EID {
            get {
                return this.EIDField;
            }
            set {
                if ((this.EIDField.Equals(value) != true)) {
                    this.EIDField = value;
                    this.RaisePropertyChanged("EID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReference {
            get {
                return this.EmployeeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeReferenceField, value) != true)) {
                    this.EmployeeReferenceField = value;
                    this.RaisePropertyChanged("EmployeeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Mission Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionField, value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw MissionReference {
            get {
                return this.MissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionReferenceField, value) != true)) {
                    this.MissionReferenceField = value;
                    this.RaisePropertyChanged("MissionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StopDate {
            get {
                return this.StopDateField;
            }
            set {
                if ((this.StopDateField.Equals(value) != true)) {
                    this.StopDateField = value;
                    this.RaisePropertyChanged("StopDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelAdvances", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TravelAdvances : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Mission MissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw MissionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Approved {
            get {
                return this.ApprovedField;
            }
            set {
                if ((this.ApprovedField.Equals(value) != true)) {
                    this.ApprovedField = value;
                    this.RaisePropertyChanged("Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EID {
            get {
                return this.EIDField;
            }
            set {
                if ((this.EIDField.Equals(value) != true)) {
                    this.EIDField = value;
                    this.RaisePropertyChanged("EID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReference {
            get {
                return this.EmployeeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeReferenceField, value) != true)) {
                    this.EmployeeReferenceField = value;
                    this.RaisePropertyChanged("EmployeeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Mission Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionField, value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw MissionReference {
            get {
                return this.MissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionReferenceField, value) != true)) {
                    this.MissionReferenceField = value;
                    this.RaisePropertyChanged("MissionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TID {
            get {
                return this.TIDField;
            }
            set {
                if ((this.TIDField.Equals(value) != true)) {
                    this.TIDField = value;
                    this.RaisePropertyChanged("TID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Expense", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Expense : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CCIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.CostCenter CostCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfCostCenterEo6k46yw CostCenterReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EXPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw ReportReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VATField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CCID {
            get {
                return this.CCIDField;
            }
            set {
                if ((this.CCIDField.Equals(value) != true)) {
                    this.CCIDField = value;
                    this.RaisePropertyChanged("CCID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.CostCenter CostCenter {
            get {
                return this.CostCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.CostCenterField, value) != true)) {
                    this.CostCenterField = value;
                    this.RaisePropertyChanged("CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfCostCenterEo6k46yw CostCenterReference {
            get {
                return this.CostCenterReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CostCenterReferenceField, value) != true)) {
                    this.CostCenterReferenceField = value;
                    this.RaisePropertyChanged("CostCenterReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EXPID {
            get {
                return this.EXPIDField;
            }
            set {
                if ((this.EXPIDField.Equals(value) != true)) {
                    this.EXPIDField = value;
                    this.RaisePropertyChanged("EXPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPID {
            get {
                return this.REPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.REPIDField, value) != true)) {
                    this.REPIDField = value;
                    this.RaisePropertyChanged("REPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw ReportReference {
            get {
                return this.ReportReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportReferenceField, value) != true)) {
                    this.ReportReferenceField = value;
                    this.RaisePropertyChanged("ReportReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VAT {
            get {
                return this.VATField;
            }
            set {
                if ((this.VATField.Equals(value) != true)) {
                    this.VATField = value;
                    this.RaisePropertyChanged("VAT");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CostCenter", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CostCenter : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CCIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Expense> ExpenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CCID {
            get {
                return this.CCIDField;
            }
            set {
                if ((this.CCIDField.Equals(value) != true)) {
                    this.CCIDField = value;
                    this.RaisePropertyChanged("CCID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Expense> Expense {
            get {
                return this.ExpenseField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpenseField, value) != true)) {
                    this.ExpenseField = value;
                    this.RaisePropertyChanged("Expense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/VitsWCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Report : Vits.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Deviation> DeviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte EIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Employee EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Expense> ExpenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpensesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.Mission MissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw MissionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.Subsistence> SubsistenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Car {
            get {
                return this.CarField;
            }
            set {
                if ((this.CarField.Equals(value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Deviation> Deviation {
            get {
                return this.DeviationField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviationField, value) != true)) {
                    this.DeviationField = value;
                    this.RaisePropertyChanged("Deviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EID {
            get {
                return this.EIDField;
            }
            set {
                if ((this.EIDField.Equals(value) != true)) {
                    this.EIDField = value;
                    this.RaisePropertyChanged("EID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw EmployeeReference {
            get {
                return this.EmployeeReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeReferenceField, value) != true)) {
                    this.EmployeeReferenceField = value;
                    this.RaisePropertyChanged("EmployeeReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Expense> Expense {
            get {
                return this.ExpenseField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpenseField, value) != true)) {
                    this.ExpenseField = value;
                    this.RaisePropertyChanged("Expense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expenses {
            get {
                return this.ExpensesField;
            }
            set {
                if ((this.ExpensesField.Equals(value) != true)) {
                    this.ExpensesField = value;
                    this.RaisePropertyChanged("Expenses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Miles {
            get {
                return this.MilesField;
            }
            set {
                if ((this.MilesField.Equals(value) != true)) {
                    this.MilesField = value;
                    this.RaisePropertyChanged("Miles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.Mission Mission {
            get {
                return this.MissionField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionField, value) != true)) {
                    this.MissionField = value;
                    this.RaisePropertyChanged("Mission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw MissionReference {
            get {
                return this.MissionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionReferenceField, value) != true)) {
                    this.MissionReferenceField = value;
                    this.RaisePropertyChanged("MissionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPID {
            get {
                return this.REPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.REPIDField, value) != true)) {
                    this.REPIDField = value;
                    this.RaisePropertyChanged("REPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.Subsistence> Subsistence {
            get {
                return this.SubsistenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubsistenceField, value) != true)) {
                    this.SubsistenceField = value;
                    this.RaisePropertyChanged("Subsistence");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Vits.ServiceReference1.EntityKeyMember> EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Vits.ServiceReference1.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfEmployeeEo6k46yw", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfEmployeeEo6k46yw : Vits.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfMissionEo6k46yw", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfMissionEo6k46yw : Vits.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Report))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Deviation>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Deviation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Mission>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Mission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Employee>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Office))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Office>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Subsistence>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Subsistence))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Trip>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Trip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Report>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.TravelAdvances>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.TravelAdvances))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.Expense>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.Expense))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.CostCenter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.CostCenter>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Vits.ServiceReference1.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfOfficeEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfCostCenterEo6k46yw))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfReportEo6k46yw", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfReportEo6k46yw : Vits.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfOfficeEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfCostCenterEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw))]
    public partial class EntityReference : Vits.ServiceReference1.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Vits.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Vits.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfEmployeeEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfCountryEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfMissionEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfOfficeEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfCostCenterEo6k46yw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vits.ServiceReference1.EntityReferenceOfReportEo6k46yw))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCountryEo6k46yw", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfCountryEo6k46yw : Vits.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfOfficeEo6k46yw", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfOfficeEo6k46yw : Vits.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCostCenterEo6k46yw", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfCostCenterEo6k46yw : Vits.ServiceReference1.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Vits.ServiceReference1.CompositeType GetDataUsingDataContract(Vits.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveReport", ReplyAction="http://tempuri.org/IService1/SaveReportResponse")]
        void SaveReport(Vits.ServiceReference1.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveOffice", ReplyAction="http://tempuri.org/IService1/SaveOfficeResponse")]
        void SaveOffice(Vits.ServiceReference1.Office office);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveMission", ReplyAction="http://tempuri.org/IService1/SaveMissionResponse")]
        void SaveMission(Vits.ServiceReference1.Mission mission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveTrip", ReplyAction="http://tempuri.org/IService1/SaveTripResponse")]
        void SaveTrip(Vits.ServiceReference1.Trip trip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveTravelAdvances", ReplyAction="http://tempuri.org/IService1/SaveTravelAdvancesResponse")]
        void SaveTravelAdvances(Vits.ServiceReference1.TravelAdvances travelAdvances);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveEmployee", ReplyAction="http://tempuri.org/IService1/SaveEmployeeResponse")]
        void SaveEmployee(Vits.ServiceReference1.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveExpense", ReplyAction="http://tempuri.org/IService1/SaveExpenseResponse")]
        void SaveExpense(Vits.ServiceReference1.Expense expense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveDeviation", ReplyAction="http://tempuri.org/IService1/SaveDeviationResponse")]
        void SaveDeviation(Vits.ServiceReference1.Deviation deviation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCountry", ReplyAction="http://tempuri.org/IService1/SaveCountryResponse")]
        void SaveCountry(Vits.ServiceReference1.Country country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCostCenter", ReplyAction="http://tempuri.org/IService1/SaveCostCenterResponse")]
        void SaveCostCenter(Vits.ServiceReference1.CostCenter costcenter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCostCenterList", ReplyAction="http://tempuri.org/IService1/GetCostCenterListResponse")]
        System.Collections.Generic.List<Vits.ServiceReference1.CostCenter> GetCostCenterList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Vits.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Vits.ServiceReference1.IService1>, Vits.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Vits.ServiceReference1.CompositeType GetDataUsingDataContract(Vits.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public void SaveReport(Vits.ServiceReference1.Report report) {
            base.Channel.SaveReport(report);
        }
        
        public void SaveOffice(Vits.ServiceReference1.Office office) {
            base.Channel.SaveOffice(office);
        }
        
        public void SaveMission(Vits.ServiceReference1.Mission mission) {
            base.Channel.SaveMission(mission);
        }
        
        public void SaveTrip(Vits.ServiceReference1.Trip trip) {
            base.Channel.SaveTrip(trip);
        }
        
        public void SaveTravelAdvances(Vits.ServiceReference1.TravelAdvances travelAdvances) {
            base.Channel.SaveTravelAdvances(travelAdvances);
        }
        
        public void SaveEmployee(Vits.ServiceReference1.Employee employee) {
            base.Channel.SaveEmployee(employee);
        }
        
        public void SaveExpense(Vits.ServiceReference1.Expense expense) {
            base.Channel.SaveExpense(expense);
        }
        
        public void SaveDeviation(Vits.ServiceReference1.Deviation deviation) {
            base.Channel.SaveDeviation(deviation);
        }
        
        public void SaveCountry(Vits.ServiceReference1.Country country) {
            base.Channel.SaveCountry(country);
        }
        
        public void SaveCostCenter(Vits.ServiceReference1.CostCenter costcenter) {
            base.Channel.SaveCostCenter(costcenter);
        }
        
        public System.Collections.Generic.List<Vits.ServiceReference1.CostCenter> GetCostCenterList() {
            return base.Channel.GetCostCenterList();
        }
    }
}
